### ISSUE TITLE
Additional PC to NX asset conversion info

### ISSUE THREAD

**Issue by SeeTheBridges** [eArmada8/ed8_inject#1]
Good evening! I'll likely write out a full guide with images to help flesh out the wiki of this Repo, but for now I just wanted to add some additional info for anyone interested in using the newly published NX script.

The Switch requirements basically come down to a hacked Switch running the latest Atmosphere build OR another custom firmware with LayeredFS support. I can't comment on anything other than Atmosphere personally though.

Converted PKGs need to be placed at: 
SD CARD/atmosphere/contents/01005420101DA000/romfs/data/asset/NX_us.zstd/C_CHR###.pkg

You can dump your assets.pka from the switch using DBI for use on PC with the new scripts. Go to:
- "Browse installed applications"
- Highlight Trails of Cold Steel 3, then press +
- Select "Expose contents via MTP". Now you can browse the game files on PC via a USB cable easily. If you have updates or DLC, you will see a TON of drives in file explorer on desktop, but the one you need should just be called LoH: Trails of Cold Steel 3.
- You'll find what you're looking for at: /romfs/data/asset/NX/assets.pka
The switch assets are 6.20 GB according to DBI.

There's some other more specific troubleshooting steps that may be needed like fixing incompatible skeletons, and determining how many PC mods can be used before affecting performance. I'll likely include them as footnotes in the full write up, but that should cover the absolute minimum to get some mods working. I can also confirm that the process has worked on other non-Altio PKGs.

Hope this helps!

**Comment by eArmada8** [comment]
Detailed in the wiki!  https://github.com/eArmada8/ed8_inject/wiki/PC-to-Switch-model-conversions
Written by SeeTheBridges
